"""
report_generator.py — Professional report generation (Markdown + PDF).

Generates downloadable analysis reports from the structured AI output.
Uses fpdf2 for PDF generation (lightweight, no system dependencies).
"""

from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Any

from fpdf import FPDF

logger = logging.getLogger(__name__)


# ── Markdown Report ──────────────────────────────────────────────────────────


def generate_markdown_report(
    analysis: dict[str, Any],
    filename: str,
    language: str,
) -> str:
    """Generate a comprehensive Markdown analysis report."""
    ov = analysis.get("overview", {})
    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    sections: list[str] = []

    # Header
    sections.append(f"# 🔍 Code Review Report")
    sections.append(f"**File:** `{filename}` | **Language:** {language} | **Generated:** {now}")
    sections.append("---")

    # Executive Summary
    sections.append("## 📋 Executive Summary")
    sections.append(f"{ov.get('summary', 'N/A')}")
    sections.append("")

    # Scores
    sections.append("## 📊 Code Health Scores")
    sections.append(f"| Metric | Value |")
    sections.append(f"|--------|-------|")
    sections.append(f"| Quality Score | **{ov.get('quality_score', 0)}/100** |")
    sections.append(f"| Complexity | **{ov.get('complexity', 'N/A')}** |")
    sections.append(f"| Total Bugs | **{ov.get('total_bugs', 0)}** |")
    sections.append(f"| Security Risk | **{ov.get('security_risk', 'N/A')}** |")
    sections.append(f"| Maintainability | **{ov.get('maintainability', 'N/A')}** |")
    sections.append("")

    # Bugs
    bugs = analysis.get("bug_analysis", [])
    sections.append(f"## 🐛 Bug Analysis ({len(bugs)} found)")
    if bugs:
        for i, bug in enumerate(bugs, 1):
            sections.append(f"### {i}. [{bug.get('severity', 'minor').upper()}] {bug.get('title', 'Untitled')}")
            sections.append(f"**Description:** {bug.get('description', 'N/A')}")
            sections.append(f"**Lines:** {bug.get('line_numbers', 'N/A')}")
            sections.append(f"**Impact:** {bug.get('impact', 'N/A')}")
            sections.append(f"**Fix:** {bug.get('suggested_fix', 'N/A')}")
            sections.append("")
    else:
        sections.append("✅ No bugs detected.")
        sections.append("")

    # Security
    sec = analysis.get("security_review", [])
    sections.append(f"## 🔒 Security Review ({len(sec)} issues)")
    if sec:
        for i, issue in enumerate(sec, 1):
            sections.append(f"### {i}. [{issue.get('severity', 'low').upper()}] {issue.get('title', 'Untitled')}")
            sections.append(f"**Category:** {issue.get('category', 'N/A')}")
            sections.append(f"**Description:** {issue.get('description', 'N/A')}")
            sections.append(f"**Recommendation:** {issue.get('recommendation', 'N/A')}")
            sections.append("")
    else:
        sections.append("✅ No security vulnerabilities detected.")
        sections.append("")

    # Optimization
    opts = analysis.get("optimization", [])
    sections.append(f"## ⚡ Optimization Suggestions ({len(opts)} items)")
    if opts:
        for i, opt in enumerate(opts, 1):
            sections.append(f"### {i}. [{opt.get('category', 'general').upper()}] {opt.get('title', 'Untitled')}")
            sections.append(f"{opt.get('description', 'N/A')}")
            if opt.get("before"):
                sections.append(f"\n**Before:**\n```\n{opt['before']}\n```")
            if opt.get("after"):
                sections.append(f"\n**After:**\n```\n{opt['after']}\n```")
            sections.append("")
    else:
        sections.append("✅ No optimizations suggested.")
        sections.append("")

    # Optimized Code
    opt_code = analysis.get("optimized_code", "")
    if opt_code:
        sections.append("## ✨ Optimized Code")
        sections.append(f"```\n{opt_code}\n```")
        sections.append("")

    sections.append("---")
    sections.append("*Generated by Intelligent Code Reviewer & Explainer*")

    return "\n".join(sections)


# ── PDF Report ───────────────────────────────────────────────────────────────


class _ReportPDF(FPDF):
    """Custom PDF with header/footer for the code review report."""

    def __init__(self, filename: str, language: str) -> None:
        super().__init__()
        self._filename = filename
        self._language = language
        self.set_auto_page_break(auto=True, margin=25)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(124, 58, 237)  # violet
        self.cell(100, 8, "Intelligent Code Reviewer & Explainer", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        info = f"{self._filename} | {self._language}"
        safe_info = info.encode("latin-1", "replace").decode("latin-1")
        self.cell(0, 8, safe_info, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(55, 65, 81)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_pdf_report(
    analysis: dict[str, Any],
    filename: str,
    language: str,
) -> bytes:
    """Generate a professional PDF analysis report and return raw bytes."""
    try:
        pdf = _ReportPDF(filename, language)
        pdf.alias_nb_pages()
        pdf.add_page()

        ov = analysis.get("overview", {})
        now = datetime.now().strftime("%B %d, %Y at %I:%M %p")

        # ── Title ────────────────────────────────────────────────────────────
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(241, 245, 249)
        pdf.cell(0, 12, "Code Review Report", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(0, 6, f"Generated: {now}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(6)

        # ── Executive Summary ────────────────────────────────────────────────
        _section_heading(pdf, "Executive Summary")
        _body_text(pdf, ov.get("summary", "N/A"))
        pdf.ln(4)

        # ── Scores Table ─────────────────────────────────────────────────────
        _section_heading(pdf, "Code Health Scores")
        scores = [
            ("Quality Score", f"{ov.get('quality_score', 0)}/100"),
            ("Complexity", str(ov.get("complexity", "N/A")).title()),
            ("Total Bugs", str(ov.get("total_bugs", 0))),
            ("Security Risk", str(ov.get("security_risk", "N/A")).title()),
            ("Maintainability", str(ov.get("maintainability", "N/A"))),
        ]
        for label, value in scores:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(203, 213, 225)
            pdf.cell(60, 7, label)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(241, 245, 249)
            pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # ── Bugs ─────────────────────────────────────────────────────────────
        bugs = analysis.get("bug_analysis", [])
        _section_heading(pdf, f"Bug Analysis ({len(bugs)} found)")
        if bugs:
            for bug in bugs:
                _sub_heading(pdf, f"[{bug.get('severity', 'minor').upper()}] {bug.get('title', 'Untitled')}")
                _body_text(pdf, f"Description: {bug.get('description', 'N/A')}")
                _body_text(pdf, f"Impact: {bug.get('impact', 'N/A')}")
                _body_text(pdf, f"Fix: {bug.get('suggested_fix', 'N/A')}")
                pdf.ln(2)
        else:
            _body_text(pdf, "No bugs detected.")
        pdf.ln(4)

        # ── Security ─────────────────────────────────────────────────────────
        sec = analysis.get("security_review", [])
        _section_heading(pdf, f"Security Review ({len(sec)} issues)")
        if sec:
            for issue in sec:
                _sub_heading(pdf, f"[{issue.get('severity', 'low').upper()}] {issue.get('title', 'Untitled')}")
                _body_text(pdf, f"Category: {issue.get('category', 'N/A')}")
                _body_text(pdf, f"Description: {issue.get('description', 'N/A')}")
                _body_text(pdf, f"Recommendation: {issue.get('recommendation', 'N/A')}")
                pdf.ln(2)
        else:
            _body_text(pdf, "No security vulnerabilities detected.")
        pdf.ln(4)

        # ── Optimization ─────────────────────────────────────────────────────
        opts = analysis.get("optimization", [])
        _section_heading(pdf, f"Optimization Suggestions ({len(opts)} items)")
        if opts:
            for opt in opts:
                _sub_heading(pdf, f"[{opt.get('category', '').upper()}] {opt.get('title', 'Untitled')}")
                _body_text(pdf, opt.get("description", "N/A"))
                pdf.ln(2)
        else:
            _body_text(pdf, "No optimizations suggested.")

        return pdf.output()
    except Exception as exc:
        logger.exception("PDF generation failed")
        raise exc


# ── PDF Helpers ──────────────────────────────────────────────────────────────


def _section_heading(pdf: FPDF, text: str) -> None:
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")


def _sub_heading(pdf: FPDF, text: str) -> None:
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(241, 245, 249)
    safe = text.encode("latin-1", "replace").decode("latin-1")
    pdf.cell(0, 7, safe, new_x="LMARGIN", new_y="NEXT")


def _body_text(pdf: FPDF, text: str) -> None:
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(203, 213, 225)
    safe = text.encode("latin-1", "replace").decode("latin-1")
    pdf.multi_cell(0, 5, safe, new_x="LMARGIN", new_y="NEXT")
